#!/bin/sh

##PBS -o STDDIR/
#PBS -j oe
#PBS -N fv3gfs_test
#PBS -l walltime=00:30:00
#PBS -q debug
#PBS -A GFS-DEV
#PBS -l place=vscatter,select=2:ncpus=96:mem=300GB
## For GEFS
##PBS -l place=vscatter,select=2:ncpus=48:mem=300GB
#PBS -V
#PBS -W umask=022

cd $PBS_O_WORKDIR

set -x

# specify computation resource
export threads=1
export MP_LABELIO=yes
export OMP_NUM_THREADS=$threads
#export APRUN="mpiexec -l -ppn 48 -n 96 --cpu-bind verbose --depth 1"
#export APRUN="mpiexec -l -n 112 -ppn 12 --cpu-bind core --depth 1"
export APRUN="mpiexec -ppn 48 -n 96"

# For GEFS
#export APRUN="mpiexec -ppn 24 -n 48"

export APRUN_DWN="mpiexec -np 24 -cpu-bind verbose,core cfp"
export machine=WCOSS2

echo "starting time $PBS_JOBNAME"
date

############################################
# Loading module
############################################
module purge
. $MODULESHOME/init/sh
module load envvar/1.0
module load intel/19.1.3.304
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load cray-mpich/8.1.7
module load cray-pals/1.0.12
module load cfp/2.0.4

module load hdf5/1.10.6
module load netcdf/4.7.4
module load crtm/2.3.0

module load prod_util/2.0.5
module load prod_envir/2.0.4
module load libjpeg/9c
module load grib_util/1.2.2
module load wgrib2/2.0.7
# memory leak
#module load valgrind4hpc/2.12.10

module list


#export WGRIB2=/u/Wen.Meng/bin/wgrib2

msg="Starting fv3gfs test"

#export svndir=`pwd`
#export svndir=/u/Wen.Meng/noscrub/ncep_post/gfsv16/EMC_post
#rundir=/u/Wen.Meng/ptmp
#homedir=/u/Wen.Meng/noscrubd/ncep_post/post_regression_test_new

# specify user's own post working directory for testing
export POSTGPEXEC=${POSTGPEXEC:-$svndir/exec/$exec}

# specify PDY (the cycle start yyyymmdd) and cycle
#export CDATE=2018042000
export CDATE=CURRENTDATE
export PDY=`echo $CDATE | cut -c1-8`
export cyc=`echo $CDATE | cut -c9-10`
export cycle=t${cyc}z


# specify the directory environment for executable, it's either para or prod
export envir=prod

####################################
# Specify RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}

# set up running dir
export job=${RUN}_post_${cyc}
export pid=${pid:-$$}
export jobid=${job}.${pid}

#mkdir -p $DATA/logs
#export jlogfile=$DATA/logs/jlogfile.${job}.${pid}

####################################
# SENDSMS  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SENDCOM=YES
export SENDDBN=NO
export RERUN=NO
export VERBOSE=YES

export HOMEgfs=${svndir}

##############################################
# Define COM directories
##############################################
#export COMIN=$COMINP/gfs.${PDY}/${cyc}
export COMIN=${COMIN:-$COMINP/gfs.${PDY}/${cyc}/atmos}
# specify my own COMOUT dir to mimic operations
export COMOUT=$rundir/com/${RUN}.$PDY/${cyc}
mkdir -p $COMOUT

# specify variables if testing post in non gfs structure environment
export POSTGRB2TBL=${HOMEgfs}/parm/params_grib2_tbl_new
export PARMpost=${HOMEgfs}/parm

export PGBF=NO
export PGB1F=NO
export FLXF=NO
export GOESF=NO
export WAFSF=YES
export KEEPDATA=YES
export OUTPUT_FILE=netcdf


#############################################################

for post_times in $allfhr; do

    export DATA=$rundir/working.upp.$post_times
    rm -rf ${DATA}
    mkdir -p $DATA
    cd $DATA

    export post_times

    date

    $HOMEgfs/jobs/J_NCEPPOST

    echo $?

    date

done

#############################################################

