#!/bin/ksh
set -x
cd /meso/save/Geoffrey.Manikin/wafs 
ymdh=`cut -c 7-16 /com/date/t12z`
echo $ymdh
ymdhm1="`/meso/save/Geoffrey.Manikin/wafs/advtime ${ymdh} -24 -1`"
echo $ymdhm1
ymdm1=`echo $ymdhm1 | cut -c1-8`
echo $ymdm1
/meso/save/Geoffrey.Manikin/wafs/faa_qsub_daily_test.sh ${ymdm1}
exit
