#!/bin/ksh
set -x
cd /meso/save/Geoffrey.Manikin/wafs 
ymdh=2015091512
echo $ymdh
ymdhm1="`/meso/save/Geoffrey.Manikin/wafs/advtime ${ymdh} -24 -1`"
echo $ymdhm1
ymdm1=`echo $ymdhm1 | cut -c1-8`
echo $ymdm1
/meso/save/Geoffrey.Manikin/wafs/faa_qsub_daily.sh ${ymdm1}
exit
