#! /bin/ksh
#
#BSUB -J wafs.ftp
#BSUB -oo /meso/save/Geoffrey.Manikin/wafs/wafsftp.out
#BSUB -eo /meso/save/Geoffrey.Manikin/wafs/wafsftp.out
#BSUB -n 1
#BSUB -W 00:30
#BSUB -q transfer
#BSUB -P GFS-MTN
#BSUB -R "affinity[core]"
#BSUB -R "rusage[mem=300]"

set -x

cd /stmpp1/Geoffrey.Manikin/wafs

scp gdas* wd20mg@emcrzdm:/home/people/emc/ftp/mmb/mmbpll/wafs/.
scp wafs* wd20mg@emcrzdm:/home/people/emc/ftp/mmb/mmbpll/wafs/.

exit
