#!/bin/sh
set -xa

#################################################################
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
# 3/10/2015, Yali Mao    For WAFS Icing temperature UV verification
#################################################################

###############################
# Specify RUN name
###############################
export NET=verf
export RUN=wafs
export envir=${envir:-prod}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
# The actual value doesn't matter for verification.
# But it must be set
export cyc=${cyc:-12}

export PS4='$SECONDS + '
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${jobid:?}}

rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$DATA/logs/jlogfiles/jlogfile.$$}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

# must exist; otherwise the following $DATA/PDY won't work
export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export HOMEverf_g2g=${HOMEverf_g2g:-/nw${envir}/verf_g2g.${model_ver}}
export EXECverf_g2g=${EXECverf_g2g:-$HOMEverf_g2g/exec}
export FIXverf_g2g=${FIXverf_g2g:-$HOMEverf_g2g/fix}
export PARMverf_g2g=${PARMverf_g2g:-$HOMEverf_g2g/parm}
export USHverf_g2g=${USHverf_g2g:-$HOMEverf_g2g/ush}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export vday=${vday:-$PDYm1}

##################################
# Define COMIN/COMOUT variables
##################################

#Raw input of WAFS icing forecast
#---------------------------------
# Global WAFS icing forecast, $PDY will be appended.
export COMINUS=${COMINUS:-$COMROOT/gfs/${envir}/gfs} # US mean max
export COMINUK=${COMINUK:-$DCOMROOT/us007003}            # UK mean max
export COMINBLND=${COMINBLND:-$COMROOT/gfs/${envir}/gfs} # blended
export COMINGFIP=${COMINGFIP:-$COMROOT/gfs/${envir}/gfs} # high resolution
# Regional icing forecast, $PDY will be appended.
export COMINFIP=${COMINFIP:-$DCOMROOT/us007003}
# Raw input of WAFS icing validation/analysis data
#---------------------------------
export CIPDIR=${CIPDIR:-$DCOMROOT/us007003}
# $PDY will be appended.
export GCIPDIR=${GCIPDIR:-$COMROOT/gfs/${envir}/gfs}
# Raw input of Wind/Temp, forecast
#---------------------------------
export COMINGFSP=${COMINGFSP:-$COMROOT/gfs/${envir}/gfs}  # U/V/T
# Raw input of Wind/Temp, validation/analysis
#---------------------------------
export COMINGFSV=${COMINGFSV:-$COMROOT/gfs/${envir}/gfs}  # U/V/T

# Processed inputs for all forecast and analysis
#---------------------------------
# folder base for processed inputs
export COM_OUT=${COM_OUT:-$COMROOT/$NET/${envir}}
# location of processed inputs, general for all dates
export FCSTDIR=$COM_OUT/${RUN} # vday will be appended
export OBSVDIR=$COM_OUT/${RUN} # vday will be appended
# location of processed inputs, for $vday after this run
export COMOUT=$COM_OUT/${RUN}.$vday

# Final VSDB output
export COMVSDB=${COMVSDB:-$COMROOT/verf/${envir}/vsdb/grid2grid}
export COMVSDB=$COMVSDB/${RUN}

mkdir -p -m 775 $COMOUT $COMVSDB

env

#######################################################################
# Execute the script.
export VMODELS=${VMODELS:-"|cip|gcipconus|gcip|gfs|"}
sh $HOMEverf_g2g/scripts/exverf_g2g_wafs.sh.ecf $vday $VMODELS

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

date

