#!/bin/ksh
set -xa
#######################################################
# This job processes the GRID2GRID cloud verification
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

###############################
# Specify RUN name
###############################
export NET=verf
export RUN=cloud

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod ]; then
#if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$$}
  export COM_OUT=${COM_OUT:-/com/verf/${envir}}
  export COM_IN=${COM_IN:-/com/verf/${envir}}
  export COMIN=$COM_IN/${RUN}.$vday
  export COMOUT=$COM_OUT/${RUN}.$vday
  export COMRAP=/com/rap/prod/rap
  export COMSREF=/com/sref/prod/sref
  export COMNAMNEST=/com/nam/prod/nam
  export COMHIRESW=/com/hiresw/prod/hiresw
  export COMNAMFIREWX=/com/nam/prod/nam
  export COMNAM=/com/nam/prod/nam
  export COMMOSAIC=/com/hourly/prod/radar
  export COMURMA=/com/urma/prod/urma2p5
  export COMBUFR=/com/hourly/prod
  export COMGFS=/com/gfs/prod/gfs
  export COMHRRR=/com/hrrr/prod/hrrr
  export COMGFSANL=/com/gfs/prod/gfs
  export COMGENS=/com/gens/prod/gefs
  export FIXGFSCLIM=/nwprod/naefs.v4.0.1/fix
  export COMNDAS=/com/nam/prod/ndas
  export FIXGFSCLIM=/nwprod/naefs.v4.0.1/fix
  export COMNAEFS=/com/gens/prod/cmce
  export AFWADIR=/dcom/us007003
  export CLAVRDIR=/dcom/us007003
fi

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# SENDECF: If the job is to be running using ecFlow, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" = dev ]    ### For Developers
then
  . /u/$LOGNAME/work/grid2grid/verf_g2g.v3.0.0/parm/verf_g2g_prod_config
fi

#if [ $SENDECF = YES ]
#then
#  ecflow_client .init=${ECF_RID}
#fi

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd}
export DATA=$DATA_IN/verf_g2g_cloud_${cyc}_${envir}.$$

rm -rf $DATA
mkdir -p $DATA
cd $DATA
####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$$}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Specify codes and scripts locaton
####################################
export HOMEverf_g2g=${HOMEverf_g2g:-/nw${envir}/verf_g2g.${model_ver}}
export EXECverf_g2g=${EXECverf_g2g:-$HOMEverf_g2g/exec}
export FIXverf_g2g=${FIXverf_g2g:-$HOMEverf_g2g/fix}
export PARMverf_g2g=${PARMverf_g2g:-$HOMEverf_g2g/parm}
export USHverf_g2g=${USHverf_g2g:-$HOMEverf_g2g/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
export EXECutil=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. $DATA/PDY

export vday=$PDYm2

##################################
# Define COMIN/COMOUT variables
##################################
export COM_IN=${COM_IN:-/com/verf/${envir}}
export COM_OUT=${COM_OUT:-/com/verf/${envir}}

export COMIN=$COM_IN/${RUN}.$vday
export COMOUT=$COM_OUT/${RUN}.$vday

export FCSTDIR=${FCSTDIR:-$COM_OUT/cloud}
export OBSVDIR=${OBSVDIR:-$COM_OUT/cloud}

export COMVSDB=${COMVSDB:-/com/verf/${envir}/vsdb/grid2grid}

mkdir -p -m 775 $COMOUT $COMVSDB/${RUN}

env

#######################################################################
# Execute the script.
sh $HOMEverf_g2g/scripts/exverf_g2g_cloud.sh.ecf $vday

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#cd $DATA_IN
#if [ ${RM_TMPDIR:-NO} = YES ]; then
#  rm -rf $DATA
#fi

date

