#!/bin/ksh
#
#  This script is to run g2g Fortran executable g2g.x
#  input: user.ctl.$model which was generated by prepg2g.sh
#
#  B. Zhou Nov. 15, 2014: Upgraded to grib2
#
#
set -x

#  arange forecast and observation grib file names ############################

 read LINE
 set -A x $LINE
 model=${x[0]}
 YYYYMMDDHH=${x[1]}
 head=${model:0:4} 

#After ensemble, use fcst.indx.$model and fcst.grib.$model instead of fcst.grib fcst.indx 
# mv fcst.grib.$model fcst.grib
# mv fcst.indx.$model fcst.indx
# mv obsv.grib.$model obsv.grib
# mv obsv.indx.$model obsv.indx

 #### following are just for tendency:
 if [ -s fcst03.grib.$model ] ; then
  mv fcst03.grib.$model fcst03.grib
  mv fcst03.indx.$model fcst03.indx
  mv obsv03.grib.$model obsv03.grib
  mv obsv03.indx.$model obsv03.indx
 fi

 if [ -s fcst06.grib.$model ] ; then
  mv fcst06.grib.$model fcst06.grib
  mv fcst06.indx.$model fcst06.indx
  mv obsv06.grib.$model obsv06.grib
  mv obsv06.indx.$model obsv06.indx
 fi

 if [ -s fcst12.grib.$model ] ; then
  mv fcst12.grib.$model fcst12.grib
  mv fcst12.indx.$model fcst12.indx
  mv obsv12.grib.$model obsv12.grib
  mv obsv12.indx.$model obsv12.indx   
 fi
  
 if [ -s fcst24.grib.$model ] ; then
  mv fcst24.grib.$model fcst24.grib
  mv fcst24.indx.$model fcst24.indx
  mv obsv24.grib.$model obsv24.grib
  mv obsv24.indx.$model obsv24.indx
 fi
 

# run g2g executable ##############################################                 

if [ $head = 'gefs' ] || [ $head = 'naef' ] || [ $head = 'sref' ] || [ $head = 'cmce' ] ; then   
  $EXECverf_g2g/verf_g2g_grid2grid < g2g.ctl.ensemble > output.ensemble
else
  $EXECverf_g2g/verf_g2g_grid2grid < g2g.ctl.$model > output.$model
fi

export err=$?; err_chk


#if [ -s ${model}_${YYYYMMDDHH}.vsdb ] ; then
#  cat grid2grid.vsdb >> ${model}_${YYYYMMDDHH}.vsdb
#  rm -f grid2grid.vsdb
#else
#  mv grid2grid.vsdb ${model}_${YYYYMMDDHH}.vsdb
#fi

if [ $head = 'gefs' ] ; then
 mv  grid2grid.vsdb GEFS_${YYYYMMDDHH}.vsdb 
elif [ $head = 'naef' ] ; then
 mv grid2grid.vsdb NAEFS_${YYYYMMDDHH}.vsdb
elif [ $head = 'sref' ] ; then
 mv grid2grid.vsdb SREF_${YYYYMMDDHH}.vsdb
elif [ $head = 'cmce' ] ; then
 mv grid2grid.vsdb CMCE_${YYYYMMDDHH}.vsdb
else
 mv grid2grid.vsdb ${model}_${YYYYMMDDHH}.vsdb
fi



exit
