#!/bin/sh
#
#  This makefile is to compile grid-to-grid all codes
#  Author: Binbin Zhou
#          20 Feb 2005
#  OS: AIX (IBM-blue)
#  After compile, comp_info file is generated for compiling infomation 
#


FC=     xlf_r
ARCH     = auto
FOPTS=  -qsmp=noauto
CMD=    verf_g2g_grid2grid

SRCS=  grid2grid.f gtgdef.f readcntl.f setarea.f \
	setfcst.f setlevel.f setmodel.f setobtyp.f status.f \
	stclst.f stldsp.f stlstr.f stnumb.f stread.f strmbl.f \
	strxbl.f getregion.f getnumber.f getGRIBdata.f \
	read_area.f sl1l2.f vl1l2.f fho.f getfho.f get_hasdata.f \
	getHGTsfc.f getTndGRIBdata.f getMeanClimData.f sal1l2.f \
	getAnomlyLevMrk.f val1l2.f afho.f FITWAV_2D.f FITWAV_1D.f \
	esl1l2.f evl1l2.f rhnt.f rhet.f sl1l2_S1.f efho.f
LIBS=   /nwprod/lib/libbacio_4.a \
	/nwprod/lib/libw3_4.a \
	/nwprod/lib/libbufr_4_32.a \
	/nwprod/lib/libip_4.a \
	/nwprod/lib/libsp_4.a \
	-l essl
$(CMD): $(SRCS)
	$(FC) $(FOPTS) $(SRCS) $(LIBS) -o $(CMD)
########################################################
