#!/bin/sh

set -xa

date

# .bashrc was loaded in GCIP_GFIP_GTG_2_rzdm.cron

if [ $prod = test ] ; then # Developer's parallel
#   DATA is for running a job card
    export DATA=${DATA:-$TMP/fv3_para_working_$cyc}
    rm -r $DATA
    mkdir -p $DATA
elif [ $prod = "para" ] ; then
    export COMROOT="paraCOMROOT"
    export DATA=${DATA:-$TMP/GCIP_GFIP_GTG_2_rzdm.working}
else # prod
    echo $COMROOT
    export DATA=${DATA:-$TMP/GCIP_GFIP_GTG_2_rzdm.working}
fi
cd $DATA


script=GCIP_GFIP_GTG_2_rzdm.sh

# Use MPMD to speed up the processing
mpmdCMDfile=$TMP/GCIP_GFIP_GTG_2_rzdm.working/gfipgcipgtg2rzdm.cmdfile
rm $mpmdCMDfile

i=0
for fhr in ${fhours[@]}; do
    fhr3="$(printf %03d $(( 10#$fhr )) )"
    echo $i $HOMEsave/scripts/$script $fhr3 >> $mpmdCMDfile
    i=$(( i + 1 ))
done
if [ ! `echo $MPIRUN | cut -d " " -f1` = 'srun' ] ; then
    # If not 'srun' MPMD, do not need CPU number at the beginning of each line of gfipgcipgtg2rzdm.cmdfile
    sed 's/[^ ]* //'  -i $mpmdCMDfile
    export MP_PGMMODEL=mpmd
    MPMDRUN=$MPIRUN
else
    MPMDRUN="$MPIRUN -l --multi-prog"
fi
chmod 744 $mpmdCMDfile
$MPMDRUN $mpmdCMDfile

date
